[project]
name = "snakerl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.10.5",
    "tensorflow[and-cuda]>=2.19.0",
]
